## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import ipywidgets

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key= g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(10)

City_ID             City Country  Max Temp Current Description    Lat  \
0        6           Trelew      AR     70.61           clear sky -43.25   
1        7            Sabha      LY     67.14           clear sky  27.04   
2        8              Sur      OM     76.41           clear sky  22.57   
3        9            Vaini      TO     75.20     overcast clouds -21.20   
4       15  Arraial Do Cabo      BR     69.80       moderate rain -22.97   
5       18           Atuona      PF     78.73           clear sky  -9.80   
6       19          Mataura      NZ     72.00     overcast clouds -46.19   
7       21           Faanui      PF     79.14    scattered clouds -16.48   
8       22           Lompoc      US     66.20     overcast clouds  34.64   
9       23     Saint-Pierre      RE     68.00           clear sky -21.34   

      Lng                          Hotel Name  
0  -65.31                  Hotel Touring Club  
1   14.43       محطة ام الارانب -سبها مواصلات  
2   59.53                     Sur Plaza Hotel  
3 -175.20                 Keleti Beach Resort  
4  -42.03                 Pousada Porto Praia  
5 -139.03                         Villa Enata  
6  168.86                       Ellie's Villa  
7 -151.75  Bora-Bora Pearl Beach Resort & Spa  
8 -120.46          Holiday Inn Express Lompoc  
9   55.48                       Lindsey Hôtel

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
vacation_search = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=vacation_search)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig


Figure()

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df["City"] == "Touros"]
vacation_end = vacation_df.loc[vacation_df["City"] == "Touros"]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Nisia Floresta"]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Conde"] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "Pitimbu"]

In [6]:
vacation_start_df = pd.DataFrame(vacation_start)
vacation_end_df = pd.DataFrame(vacation_end)
vacation_stop1_df = pd.DataFrame(vacation_stop1)
vacation_stop2_df = pd.DataFrame(vacation_stop2)
vacation_stop3_df = pd.DataFrame(vacation_stop3)

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start_df[["Lat", "Lng"]].to_numpy()
end = vacation_end_df[["Lat", "Lng"]].to_numpy()
stop1 = vacation_stop1_df[["Lat", "Lng"]].to_numpy()
stop2 = vacation_stop2_df[["Lat", "Lng"]].to_numpy()
stop3 = vacation_stop3_df[["Lat", "Lng"]].to_numpy()

In [8]:
print(start)
print(end)
print(stop1)
print(stop2)
print(stop3)

[[ -5.2  -35.46]]
[[ -5.2  -35.46]]
[[ -6.09 -35.21]]
[[ -7.26 -34.91]]
[[ -7.47 -34.81]]


In [9]:
touros = (-5.2, -35.46)
touros_end = (-5.2, -35.46)
nisia_floresta = (-6.09, -35.21)
conde = (-7.26, -34.91)
pitimbu = (-7.47, -34.81)

In [13]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
# Latitude-longitude pairs

fig = gmaps.figure()
touros2touros_end_via_3stops = gmaps.directions_layer(
    touros, touros_end, waypoints=[nisia_floresta, conde, pitimbu], 
    travel_mode='DRIVING')
fig.add_layer(touros2touros_end_via_3stops)
fig


Figure()

In [37]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start_df, vacation_stop1_df, vacation_stop2_df, vacation_stop3_df],ignore_index=True)
itinerary_df

City_ID            City Country  Max Temp Current Description   Lat    Lng  \
0      301          Touros      BR      78.8    scattered clouds -5.20 -35.46   
1      612  Nisia Floresta      BR      78.8    scattered clouds -6.09 -35.21   
2      681           Conde      BR      78.8       broken clouds -7.26 -34.91   
3      580         Pitimbu      BR      78.8       broken clouds -7.47 -34.81   

           Hotel Name  
0     INN NEW HORIZON  
1   Rancho Crepusculo  
2  Pousada Beija Flor  
3    Reserva do Abiaí

In [38]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [39]:
# 11a. Add a marker layer for each city to the map.
# 4a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig
# 11b. Display the figure


Figure()